"""autogenerated by genpy from FroboMsgs/detected_objects.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class detected_objects(genpy.Message):
  _md5sum = "e3f292bb58f418ad7ba8a85cc19ed218"
  _type = "FroboMsgs/detected_objects"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int8 right_blocked
float64 closest_object_distance_right
float64 closest_object_angle_right
int8 left_blocked
float64 closest_object_distance_left
float64 closest_object_angle_left
int8 stop_zone_occupied
 

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','right_blocked','closest_object_distance_right','closest_object_angle_right','left_blocked','closest_object_distance_left','closest_object_angle_left','stop_zone_occupied']
  _slot_types = ['std_msgs/Header','int8','float64','float64','int8','float64','float64','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,right_blocked,closest_object_distance_right,closest_object_angle_right,left_blocked,closest_object_distance_left,closest_object_angle_left,stop_zone_occupied

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(detected_objects, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.right_blocked is None:
        self.right_blocked = 0
      if self.closest_object_distance_right is None:
        self.closest_object_distance_right = 0.
      if self.closest_object_angle_right is None:
        self.closest_object_angle_right = 0.
      if self.left_blocked is None:
        self.left_blocked = 0
      if self.closest_object_distance_left is None:
        self.closest_object_distance_left = 0.
      if self.closest_object_angle_left is None:
        self.closest_object_angle_left = 0.
      if self.stop_zone_occupied is None:
        self.stop_zone_occupied = 0
    else:
      self.header = std_msgs.msg.Header()
      self.right_blocked = 0
      self.closest_object_distance_right = 0.
      self.closest_object_angle_right = 0.
      self.left_blocked = 0
      self.closest_object_distance_left = 0.
      self.closest_object_angle_left = 0.
      self.stop_zone_occupied = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_b2db2db.pack(_x.right_blocked, _x.closest_object_distance_right, _x.closest_object_angle_right, _x.left_blocked, _x.closest_object_distance_left, _x.closest_object_angle_left, _x.stop_zone_occupied))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 35
      (_x.right_blocked, _x.closest_object_distance_right, _x.closest_object_angle_right, _x.left_blocked, _x.closest_object_distance_left, _x.closest_object_angle_left, _x.stop_zone_occupied,) = _struct_b2db2db.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_b2db2db.pack(_x.right_blocked, _x.closest_object_distance_right, _x.closest_object_angle_right, _x.left_blocked, _x.closest_object_distance_left, _x.closest_object_angle_left, _x.stop_zone_occupied))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 35
      (_x.right_blocked, _x.closest_object_distance_right, _x.closest_object_angle_right, _x.left_blocked, _x.closest_object_distance_left, _x.closest_object_angle_left, _x.stop_zone_occupied,) = _struct_b2db2db.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_b2db2db = struct.Struct("<b2db2db")
