"""autogenerated by genpy from frobo/fpga_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class fpga_data(genpy.Message):
  _md5sum = "378edc8b8a9c23602b7d54ff55da0269"
  _type = "frobo/fpga_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 encoder_l
uint32 encoder_r
uint32 pwm_value

"""
  __slots__ = ['encoder_l','encoder_r','pwm_value']
  _slot_types = ['uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       encoder_l,encoder_r,pwm_value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(fpga_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.encoder_l is None:
        self.encoder_l = 0
      if self.encoder_r is None:
        self.encoder_r = 0
      if self.pwm_value is None:
        self.pwm_value = 0
    else:
      self.encoder_l = 0
      self.encoder_r = 0
      self.pwm_value = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.encoder_l, _x.encoder_r, _x.pwm_value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.encoder_l, _x.encoder_r, _x.pwm_value,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.encoder_l, _x.encoder_r, _x.pwm_value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.encoder_l, _x.encoder_r, _x.pwm_value,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
