"""autogenerated by genpy from frobo/laser_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class laser_info(genpy.Message):
  _md5sum = "92ab7036c14619d38f8cd23fdb2470a8"
  _type = "frobo/laser_info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool blocked
bool end_of_row
float64 force
float64 carefull

"""
  __slots__ = ['blocked','end_of_row','force','carefull']
  _slot_types = ['bool','bool','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       blocked,end_of_row,force,carefull

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(laser_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.blocked is None:
        self.blocked = False
      if self.end_of_row is None:
        self.end_of_row = False
      if self.force is None:
        self.force = 0.
      if self.carefull is None:
        self.carefull = 0.
    else:
      self.blocked = False
      self.end_of_row = False
      self.force = 0.
      self.carefull = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B2d.pack(_x.blocked, _x.end_of_row, _x.force, _x.carefull))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.blocked, _x.end_of_row, _x.force, _x.carefull,) = _struct_2B2d.unpack(str[start:end])
      self.blocked = bool(self.blocked)
      self.end_of_row = bool(self.end_of_row)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B2d.pack(_x.blocked, _x.end_of_row, _x.force, _x.carefull))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.blocked, _x.end_of_row, _x.force, _x.carefull,) = _struct_2B2d.unpack(str[start:end])
      self.blocked = bool(self.blocked)
      self.end_of_row = bool(self.end_of_row)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B2d = struct.Struct("<2B2d")
